id: P000482
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-16 15:42:15.864948
source_metadata:
  id: bdr:W1PD105902
  title: སངས་རྒྱས་ཆོས་ལུགས་དང་བོད་ཀྱི་རིག་གནས་སྐོར་གླེང་བ།
  author: ''
  volumes:
    4496172497e8485b84f0b3a701264fff:
      image_group_id: I1PD105904
      title: Volume 1 of sangs rgyas chos lugs dang bod kyi rig gnas las 'phros pa'i
        gnad don skor gleng ba bden gtam
      volume_number: 1
      total_pages: 270
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
