id: I354014C3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:12:36+00:00'
last_modified: '2022-06-10T06:33:34.601635+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD105902
  title: སངས་རྒྱས་ཆོས་ལུགས་དང་བོད་ཀྱི་རིག་གནས་སྐོར་གླེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    2CDD:
      image_group_id: I1PD105904
      title: Volume 1 of sangs rgyas chos lugs dang bod kyi rig gnas las 'phros pa'i
        gnad don skor gleng ba bden gtam
      total_pages: 270
      order: 1
      base_file: 2CDD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
